version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - echo Checking out source code...
      - git checkout main  
      - git pull origin main
  build:
    commands:
      - echo Building the project...
      - npm run build
artifacts:
  files:
    - dist/**/*
    - appspec.yml
    - scripts/**/* 
  base-directory: .
